
USE [master]
GO

/****** Object:  Database [StyleVietDB]    Script Date: 12/12/2018 9:56:34 PM ******/
CREATE DATABASE [StyleVietDB]
-- CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'StyleVietDB', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\StyleVietDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
-- LOG ON 
--( NAME = N'StyleVietDB_log', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\StyleVietDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [StyleVietDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StyleVietDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StyleVietDB] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [StyleVietDB] SET ANSI_NULLS OFF
GO

ALTER DATABASE [StyleVietDB] SET ANSI_PADDING OFF
GO

ALTER DATABASE [StyleVietDB] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [StyleVietDB] SET ARITHABORT OFF
GO

ALTER DATABASE [StyleVietDB] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [StyleVietDB] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [StyleVietDB] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [StyleVietDB] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [StyleVietDB] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [StyleVietDB] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [StyleVietDB] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [StyleVietDB] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [StyleVietDB] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [StyleVietDB] SET  ENABLE_BROKER
GO

ALTER DATABASE [StyleVietDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [StyleVietDB] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [StyleVietDB] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [StyleVietDB] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [StyleVietDB] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [StyleVietDB] SET READ_COMMITTED_SNAPSHOT ON
GO

ALTER DATABASE [StyleVietDB] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [StyleVietDB] SET RECOVERY FULL
GO

ALTER DATABASE [StyleVietDB] SET  MULTI_USER
GO

ALTER DATABASE [StyleVietDB] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [StyleVietDB] SET DB_CHAINING OFF
GO

ALTER DATABASE [StyleVietDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [StyleVietDB] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [StyleVietDB] SET DELAYED_DURABILITY = DISABLED
GO

EXEC sys.sp_db_vardecimal_storage_format N'StyleVietDB', N'ON'
GO

ALTER DATABASE [StyleVietDB] SET QUERY_STORE = OFF
GO

USE [StyleVietDB]
GO

/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 12/12/2018 9:56:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Account]    Script Date: 12/12/2018 9:56:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[AccountRole]    Script Date: 12/12/2018 9:56:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Admin]    Script Date: 12/12/2018 9:56:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Category]    Script Date: 12/12/2018 9:56:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Gallery]    Script Date: 12/12/2018 9:56:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Role]    Script Date: 12/12/2018 9:56:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Salon]    Script Date: 12/12/2018 9:56:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[SalonService]    Script Date: 12/12/2018 9:56:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Service]    Script Date: 12/12/2018 9:56:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[User]    Script Date: 12/12/2018 9:56:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20181210101147_InitialDB', N'2.1.4-rtm-31024')
GO

INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20181210101900_AddLinkAccountToSalon', N'2.1.4-rtm-31024')
GO

INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20181212094734_Remove_RoleId_In_Account', N'2.1.4-rtm-31024')
GO

SET IDENTITY_INSERT [dbo].[Account] ON
GO

INSERT [dbo].[Account] ([Id], [Username], [Password], [Email], [Expired]) VALUES (7, N'TPaCmqk3KOjzyX35E/sb+pX+WBDikzoFlD+DEqmNnPI=', N'1HtaY+LK7nT0h9HbN+PgN/c4cDbobJM5VVfD8l2/AN8=lTPzk3P', N'tiendatdeveloper1997@gmail.com', 0)
GO

SET IDENTITY_INSERT [dbo].[Account] OFF
GO

INSERT [dbo].[AccountRole] ([AccountId], [RoleId]) VALUES (7, 1)
GO

SET IDENTITY_INSERT [dbo].[Admin] ON
GO

INSERT [dbo].[Admin] ([Id], [Fullname], [Phone], [AccountId]) VALUES (6, N'Trần Tiến Đạt', N'0343734810', 7)
GO

SET IDENTITY_INSERT [dbo].[Admin] OFF
GO

SET IDENTITY_INSERT [dbo].[Role] ON
GO

INSERT [dbo].[Role] ([Id], [Name]) VALUES (1, N'Admin')
GO

INSERT [dbo].[Role] ([Id], [Name]) VALUES (2, N'Salon')
GO

INSERT [dbo].[Role] ([Id], [Name]) VALUES (3, N'Member')
GO

SET IDENTITY_INSERT [dbo].[Role] OFF
GO

/****** Object:  StoredProcedure [dbo].[RegisterAdminAccount]    Script Date: 12/12/2018 9:56:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [StyleVietDB] SET  READ_WRITE
GO
